//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgroCoops.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDAgriculturaEntities : DbContext
    {
        public BDAgriculturaEntities()
            : base("name=BDAgriculturaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cooperativa> cooperativa { get; set; }
        public virtual DbSet<entrada> entrada { get; set; }
        public virtual DbSet<estoque> estoque { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<pedidoEstoque> pedidoEstoque { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<pessoaFisica> pessoaFisica { get; set; }
        public virtual DbSet<pessoaJuridica> pessoaJuridica { get; set; }
        public virtual DbSet<produto> produto { get; set; }
        public virtual DbSet<produtor> produtor { get; set; }
        public virtual DbSet<valorUnitario> valorUnitario { get; set; }
    }
}
