//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrada
    {
        public int idEntrada { get; set; }
        public int idProdutor { get; set; }
        public int idCooperativa { get; set; }
        public int idProduto { get; set; }
        public int quantidadeEntrada { get; set; }
        public System.DateTime dataEntrada { get; set; }
    
        public virtual cooperativa cooperativa { get; set; }
        public virtual produtor produtor { get; set; }
    }
}
