//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoaFisica
    {
        public int idPessoa { get; set; }
        public long cpf { get; set; }
        public string sexo { get; set; }
        public System.DateTime dataNascimento { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual produtor produtor { get; set; }
    }
}
