//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoaJuridica
    {
        public int idPessoa { get; set; }
        public long cnpj { get; set; }
        public string nomeFantasia { get; set; }
    
        public virtual pessoa pessoa { get; set; }
    }
}
