//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoAgroCoops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class valorUnitario
    {
        public int idValorUnitario { get; set; }
        public int idProduto { get; set; }
        public int idCooperativa { get; set; }
        public System.DateTime dataValorUnitario { get; set; }
        public decimal valorUnitario1 { get; set; }
    
        public virtual cooperativa cooperativa { get; set; }
        public virtual produto produto { get; set; }
    }
}
